name: Test
on: pull_request

jobs:
  testLinux:
    name: Test Conda Linux
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: foo
          environment-file: .environmentLinux.yaml
          python-version: 3.8
          auto-activate-base: false
      - run: |
          pip install .
          nosetests -sv

  test-builds:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'   
    - name: Install build prerequisites
      run: |
        python -m pip install --upgrade build numpy
    - name: Install cibuildwheel
      run: |
        python -m pip install --upgrade cibuildwheel      
    - name: Build wheel(s)
      run: |
        python -m cibuildwheel --output-dir wheelhouse
    - name: Build sdist
      run: |
        python -m build --sdist
    - uses: actions/upload-artifact@v3
      with:
        name: pyBigWig-build
        path: |
          wheelhouse/*
          dist/pyBigWig*.tar.gz
